### PR TITLE
add 32 founds (2024-03-27)

### PR DESCRIPTION
**Pull request by roycewilliams**
Been a while - found a few!

### CODE REVIEW

**Comment by roycewilliams** [comment]
Looks like automation picked up the changes indirectly - closing.

**Comment by Janmm14** [comment]
@roycewilliams No, the automation cannot pick up the nonstandard founds. Multiple with capital first letter and one where the `.` after the `*` are missing from the automation.

**Comment by sudofox** [comment]
Ooh! The project awakens! I'll take a look soon

**Comment by sudofox** [comment]
@roycewilliams The reason I didn't fix the merge conflict was moreso because I wanted to let the scripts handle the new solves so that things would be sorted already. But I put your username in the commit message. I hope that's okay

Thanks so much!!

**Comment by roycewilliams** [comment]
Works for me - thanks!

**Pull request closed without merging**
