### PR TITLE
Kalicorp Bypass Domain

### PR DESCRIPTION
**Pull request by PureFallen**
Domain used to bypass Mojang Blocklist after `*.kalicorp.fr` has been blocked.

I apologize if i have put the domain at the wrong place in `merged.txt`, i couldn't notice any system other than maybe grouping domains of the same server together?

### CODE REVIEW

**Comment by sudofox** [comment]
Thanks!

You should be using `node try_url.js` to add newly discovered strings, and then you can run those little npm scripts in the package.json to generate the other files, such as merged.txt.

- `merged.txt` maintains the same order as current.txt (which is a copy of the Mojang API results).
- `identified.txt` is sorted in alphabetical line order.


I generally run these, in this order:

```
npm run update-blocklist ; npm run update-merged; npm run update-todo
```

Try doing that and committing the result. There's never any need to manually modify the files inside data/

**Comment by sudofox** [comment]
Note that you should do the above sooner than later because otherwise my GitHub automation will pull down the latest current.txt and it might cause a merge conflict since Mojang just removed one of the entries a bit ago

I could add the string myself but I would like to see you get credit via the contributors list :)

**Comment by sudofox** [comment]
@PureFallen I realized that aforementioned GH automation _should_ fix the order on merged.txt anyway, so I'm just going to go ahead and merge

If you find any in the future though, pay heed to what I wrote above.

**Comment by PureFallen** [comment]
Thanks! My inexperience with git was about to strike me..
Was debating what would have been the right approach in such a situation, either reverting the bad commit or history rewriting?
Quick and Dirty way could have been to redo fork & PR but there must be a cleaner solution to that.

**Pull request merged**
